/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CourtroomRouteImport } from './routes/courtroom'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppQuizzesRouteImport } from './routes/app.quizzes'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCasesRouteImport } from './routes/app.cases'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAcademyRouteImport } from './routes/app.academy'

const CourtroomRoute = CourtroomRouteImport.update({
  id: '/courtroom',
  path: '/courtroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyRoute = AppAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/courtroom': typeof CourtroomRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/cases': typeof AppCasesRoute
  '/app/community': typeof AppCommunityRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courtroom': typeof CourtroomRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/cases': typeof AppCasesRoute
  '/app/community': typeof AppCommunityRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/courtroom': typeof CourtroomRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/cases': typeof AppCasesRoute
  '/app/community': typeof AppCommunityRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/courtroom'
    | '/app/academy'
    | '/app/assistant'
    | '/app/cases'
    | '/app/community'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courtroom'
    | '/app/academy'
    | '/app/assistant'
    | '/app/cases'
    | '/app/community'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/courtroom'
    | '/app/academy'
    | '/app/assistant'
    | '/app/cases'
    | '/app/community'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/settings'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CourtroomRoute: typeof CourtroomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/courtroom': {
      id: '/courtroom'
      path: '/courtroom'
      fullPath: '/courtroom'
      preLoaderRoute: typeof CourtroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes': {
      id: '/app/quizzes'
      path: '/quizzes'
      fullPath: '/app/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academy': {
      id: '/app/academy'
      path: '/academy'
      fullPath: '/app/academy'
      preLoaderRoute: typeof AppAcademyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademyRoute: typeof AppAcademyRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCasesRoute: typeof AppCasesRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppProgressRoute: typeof AppProgressRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademyRoute: AppAcademyRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCasesRoute: AppCasesRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppProgressRoute: AppProgressRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CourtroomRoute: CourtroomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
